name: Webhook Events

on:
  push:
  pull_request:
  merge:

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook
        uses: distributhor/webhook-action@v1
        with:
          url: 'https://your-webhook-endpoint.com'



